links:
  appeals: ''
  twitter: ''
  facebook: ''
  discord: ''
  youtube: ''
  forum: ''
  instagram: ''
  reports: ''
  webstore: ''

vote:
- 'PlanetMinecraft'
- 'MCSL'

messages:
  linkSet: '<green>You set the<gray> %link% <green>to: '
  noPermission: '<red>You do not have the<dark_red> %permission% <red>permission!'
  prefix: '<gray>[<dark_aqua>ServerLinks<gray>] <reset>'
  invalidCmd: '<red>Unknown command or arguments. Are you sure you are using the correct command?'
  configReloaded: '<green>Configuration reloaded successfully!'
  linkReset: '<green>You reset the<gray> %link%<green>.'
  noLinkSet: '<red>No link has been set. Please contact an administrator.'
  linkUsage: '<red>Usage: /sl link <link>'
  setUsage: '<red>Usage: /sl set <link> <message>'
  resetUsage: '<red>Usage: /sl reset <link>'
  linksNotSet: '<red>No links have been set!'
  guiName: '<dark_aqua>ServerLinks'
  guiItemColor: '<dark_aqua>'