main: me.number3504.serverlinks.Main
name: ServerLinks
version: @version@
api-version: 1.19
author: Altruiis
description: Plugin to set media links such as discord for your users
softdepend:
  - PlaceholderAPI

commands:
  serverlinks:
    description: Core plugin command
    aliases:
      - sl

permissions:
  links.*:
    default: op
    children:
      links.set: true
      links.reset: true
      links.reload: true
  links.set:
    default: op
  links.reset:
    default: op
  links.reload:
    default: op