main: me.number3504.serverlinks.Main
name: ServerLinks
version: 3.2
api-version: 1.16
author: Number3504
description: Plugin to set media links such as discord for your users

commands:
  serverlinks:
    description: ServerLinks main command
    aliases: sl

permissions:
  links.*:
    default: op
    children:
      links.set: true
      links.reset: true
      links.reload: true
  links.set:
    default: op
  links.reset:
    default: op
  links.reload:
    default: op