links:
  appeals: ''
  twitter: ''
  facebook: ''
  discord: ''
  youtube: ''
  forum: ''
  instagram: ''
  reports: ''
  webstore: ''

vote:
- 'PlanetMinecraft'
- 'MCSL'

messages:
  linkSet: '&aYou set the&7 %link% &ato: '
  noPermission: '&cYou do not have the&4 %permission% &cpermission!'
  prefix: '&7[&3ServerLinks&7] &r'
  invalidCmd: '&cUnknown command or arguments. Are you sure you are using the correct command?'
  configReloaded: '&aConfiguration reloaded successfully!'
  linkReset: '&aYou reset the&7 %link%&a.'
  noLinkSet: '&cNo link has been set. Please contact an administrator.'
  linkUsage: '&cUsage: /ServerLinks link <link>'
  setUsage: '&cUsage: /ServerLinks set <link> <message>'
  resetUsage: '&cUsage: /ServerLinks reset <link>'
