name: "Devbuild"
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

jobs:
  pre-release:
    name: "Devbuild"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Validate gradlew
        uses: gradle/wrapper-validation-action@v1
      - name: Execute gradle
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Jar
        run: ./gradlew jar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/*.jar
      #- name: Create devbuild
      #  uses: "marvinpinto/action-automatic-releases@latest"
      #  with:
      #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #    automatic_release_tag: "latest"
      #    prerelease: true
      #    title: "Dev build"
      #    files: |
      #      build/libs/*.jar